In [2]:
import xarray as xr

In [ ]:
import netCDF4
print(netCDF4.__version__)

import h5netcdf
print(h5netcdf.__version__)

1.7.2
1.7.3

In [3]:
ds_003=xr.open_dataset("D:/Man/Earth and Environment/project2/003_2006_2080_352_360.nc")
ds_003.to_dataframe()

                                      TREFMXAV_U       FLNS       FSNS  \
time                lat       lon
2006-01-02 00:00:00 49.476440 352.50         NaN  76.479729  44.470936
                              353.75         NaN  78.499649  47.310978
                              355.00         NaN  79.779884  47.081329
                              356.25         NaN  81.951942  50.421570
                              357.50         NaN  84.151154  50.305706
...                                          ...        ...        ...
2080-12-31 00:00:00 58.900524 353.75         NaN  64.274734  12.221095
                              355.00         NaN  59.831974  10.224747
                              356.25  285.378082  55.972206   7.803443
                              357.50         NaN  55.649826   8.590393
                              358.75         NaN  56.796509   9.985412

                                             PRECT          PRSN      QBOT  \
time                lat       lon
2006-01-02 00:00:00 49.476440 352.50  1.157632e-08  0.000000e+00  0.005241
                              353.75  1.511678e-08  5.754220e-23  0.005230
                              355.00  1.400193e-08  2.408303e-23  0.005142
                              356.25  1.458894e-08  3.645272e-18  0.005161
                              357.50  1.563543e-08  1.291952e-17  0.005128
...                                            ...           ...       ...
2080-12-31 00:00:00 58.900524 353.75  4.901781e-08  1.245445e-17  0.005263
                              355.00  5.783695e-08  2.691679e-19  0.005451
                              356.25  4.789543e-08  4.516594e-17  0.005616
                              357.50  3.219014e-08  9.257918e-18  0.005677
                              358.75  2.066702e-08  0.000000e+00  0.005780

                                          TREFHT      UBOT      VBOT
time                lat       lon
2006-01-02 00:00:00 49.476440 352.50  284.357269  7.604368 -3.689787
                              353.75  284.161591  6.998310 -4.547439
                              355.00  283.876190  6.095287 -4.407815
                              356.25  283.557373  5.727140 -3.411074
                              357.50  283.177917  5.714839 -2.058823
...                                          ...       ...       ...
2080-12-31 00:00:00 58.900524 353.75  283.593170 -1.807185 -2.838642
                              355.00  283.426788 -0.644041 -2.672824
                              356.25  283.418671  0.561813 -2.916785
                              357.50  283.790833  1.941811 -3.057128
                              358.75  283.980896  3.437217 -2.624627

[1806684 rows x 9 columns]

In [4]:
ds_004=xr.open_dataset("D:/Man/Earth and Environment/project2/004_2006_2080_352_360.nc")
ds_004.to_dataframe()

                                      TREFMXAV_U       FLNS       FSNS  \
time                lat       lon
2006-01-02 00:00:00 49.476440 352.50         NaN  34.583336  14.065823
                              353.75         NaN  31.098053  16.537430
                              355.00         NaN  25.429327  21.770348
                              356.25         NaN  21.334295  23.288593
                              357.50         NaN  14.878189  22.177370
...                                          ...        ...        ...
2080-12-31 00:00:00 58.900524 353.75         NaN  78.357506  12.646336
                              355.00         NaN  80.806496  12.415510
                              356.25  282.256317  77.926613  12.313849
                              357.50         NaN  73.540985  11.417438
                              358.75         NaN  65.714958   9.995486

                                             PRECT          PRSN      QBOT  \
time                lat       lon
2006-01-02 00:00:00 49.476440 352.50  8.991014e-08  2.508268e-15  0.007942
                              353.75  9.029859e-08  2.272439e-15  0.007990
                              355.00  9.151029e-08  1.289623e-13  0.007969
                              356.25  9.553797e-08  3.858073e-14  0.007935
                              357.50  1.157726e-07  1.243580e-14  0.007802
...                                            ...           ...       ...
2080-12-31 00:00:00 58.900524 353.75  1.489864e-08  1.440664e-15  0.004894
                              355.00  2.130486e-08  9.855597e-17  0.004928
                              356.25  3.256793e-08  4.481878e-16  0.004866
                              357.50  4.358893e-08  1.863424e-16  0.004737
                              358.75  3.627807e-08  1.391026e-16  0.004702

                                          TREFHT       UBOT      VBOT
time                lat       lon
2006-01-02 00:00:00 49.476440 352.50  285.583679  10.730030  5.321742
                              353.75  285.516144  10.579328  5.534393
                              355.00  285.401428   9.594035  6.708336
                              356.25  285.186127   7.964078  8.409520
                              357.50  284.925903   5.748650  9.287416
...                                          ...        ...       ...
2080-12-31 00:00:00 58.900524 353.75  281.526001  -8.965286  4.459151
                              355.00  280.617706  -8.597703  4.964406
                              356.25  280.613922  -7.896321  6.249859
                              357.50  281.247955  -7.071263  7.631931
                              358.75  281.730927  -5.914586  8.348085

[1806684 rows x 9 columns]