In [2]:
import xarray as xr
import pandas as pd
import netCDF4
import netCDF4
import h5netcdf

In [ ]:
# read 003
ds_003=xr.open_dataset("D:/Man/Earth and Environment/project2/003_2006_2080_352_360.nc")
ds_003.to_dataframe()

                                      TREFMXAV_U       FLNS       FSNS  \
time                lat       lon
2006-01-02 00:00:00 49.476440 352.50         NaN  76.479729  44.470936
                              353.75         NaN  78.499649  47.310978
                              355.00         NaN  79.779884  47.081329
                              356.25         NaN  81.951942  50.421570
                              357.50         NaN  84.151154  50.305706
...                                          ...        ...        ...
2080-12-31 00:00:00 58.900524 353.75         NaN  64.274734  12.221095
                              355.00         NaN  59.831974  10.224747
                              356.25  285.378082  55.972206   7.803443
                              357.50         NaN  55.649826   8.590393
                              358.75         NaN  56.796509   9.985412

                                             PRECT          PRSN      QBOT  \
time                lat       lon
2006-01-02 00:00:00 49.476440 352.50  1.157632e-08  0.000000e+00  0.005241
                              353.75  1.511678e-08  5.754220e-23  0.005230
                              355.00  1.400193e-08  2.408303e-23  0.005142
                              356.25  1.458894e-08  3.645272e-18  0.005161
                              357.50  1.563543e-08  1.291952e-17  0.005128
...                                            ...           ...       ...
2080-12-31 00:00:00 58.900524 353.75  4.901781e-08  1.245445e-17  0.005263
                              355.00  5.783695e-08  2.691679e-19  0.005451
                              356.25  4.789543e-08  4.516594e-17  0.005616
                              357.50  3.219014e-08  9.257918e-18  0.005677
                              358.75  2.066702e-08  0.000000e+00  0.005780

                                          TREFHT      UBOT      VBOT
time                lat       lon
2006-01-02 00:00:00 49.476440 352.50  284.357269  7.604368 -3.689787
                              353.75  284.161591  6.998310 -4.547439
                              355.00  283.876190  6.095287 -4.407815
                              356.25  283.557373  5.727140 -3.411074
                              357.50  283.177917  5.714839 -2.058823
...                                          ...       ...       ...
2080-12-31 00:00:00 58.900524 353.75  283.593170 -1.807185 -2.838642
                              355.00  283.426788 -0.644041 -2.672824
                              356.25  283.418671  0.561813 -2.916785
                              357.50  283.790833  1.941811 -3.057128
                              358.75  283.980896  3.437217 -2.624627

[1806684 rows x 9 columns]

In [ ]:
# select all the data from Manchester and change it to csv
man_lat=53.48
man_lon=357.76
ds_003_man=ds_003.sel(lat=man_lat,lon=man_lon,method='nearest')

if hasattr(ds_003_man.indexes['time'], 'to_datetimeindex'):
    datetime_index = ds_003_man.indexes['time'].to_datetimeindex()
    ds_003_man['time'] = datetime_index

man_003=ds_003_man.to_dataframe().reset_index()

man_003['year']=man_003['time'].dt.year
man_003['month']=man_003['time'].dt.month
man_003['day']=man_003['time'].dt.day_of_year

man_003.to_csv("D:/Man/Earth and Environment/project2/003_manchester.csv",index=False)

C:\Users\Administrator\AppData\Local\Temp\ipykernel_22956\3205257280.py:7: FutureWarning: In a future version of xarray to_datetimeindex will default to returning a 'us'-resolution DatetimeIndex instead of a 'ns'-resolution DatetimeIndex. This warning can be silenced by explicitly passing the `time_unit` keyword argument.
  datetime_index = ds_003_man.indexes['time'].to_datetimeindex()
C:\Users\Administrator\AppData\Local\Temp\ipykernel_22956\3205257280.py:7: RuntimeWarning: Converting a CFTimeIndex with dates from a non-standard calendar, 'noleap', to a pandas.DatetimeIndex, which uses dates from the standard calendar.  This may lead to subtle errors in operations that depend on the length of time between dates.
  datetime_index = ds_003_man.indexes['time'].to_datetimeindex()

In [ ]:
# read 004
ds_004=xr.open_dataset("D:/Man/Earth and Environment/project2/004_2006_2080_352_360.nc")

ds_004_man=ds_004.sel(lat=man_lat,lon=man_lon,method='nearest')

if hasattr(ds_004_man.indexes['time'], 'to_datetimeindex'):
    datetime_index = ds_004_man.indexes['time'].to_datetimeindex()
    ds_004_man['time'] = datetime_index

man_004=ds_004_man.to_dataframe().reset_index()

man_004['year']=man_004['time'].dt.year
man_004['month']=man_004['time'].dt.month
man_004['day']=man_004['time'].dt.day_of_year

man_004.to_csv("D:/Man/Earth and Environment/project2/004_manchester.csv",index=False)

man_004

C:\Users\Administrator\AppData\Local\Temp\ipykernel_6320\94795858.py:9: FutureWarning: In a future version of xarray to_datetimeindex will default to returning a 'us'-resolution DatetimeIndex instead of a 'ns'-resolution DatetimeIndex. This warning can be silenced by explicitly passing the `time_unit` keyword argument.
  datetime_index = ds_004_man.indexes['time'].to_datetimeindex()
C:\Users\Administrator\AppData\Local\Temp\ipykernel_6320\94795858.py:9: RuntimeWarning: Converting a CFTimeIndex with dates from a non-standard calendar, 'noleap', to a pandas.DatetimeIndex, which uses dates from the standard calendar.  This may lead to subtle errors in operations that depend on the length of time between dates.
  datetime_index = ds_004_man.indexes['time'].to_datetimeindex()

,time,TREFMXAV_U,FLNS,FSNS,PRECT,PRSN,QBOT,TREFHT,UBOT,VBOT,lat,lon,year,month,day
0,2006-01-02,283.564941,6.118795,10.919062,8.909233e-08,1.053175e-14,0.006630,281.269958,-0.778822,2.993445,53.246075,357.5,2006,1,2
1,2006-01-03,283.994415,30.605610,13.505382,2.359809e-08,2.963242e-17,0.005252,280.115082,1.579463,4.951698,53.246075,357.5,2006,1,3
2,2006-01-04,281.907501,49.963528,29.042658,2.080145e-08,2.459500e-12,0.004472,277.866547,4.896808,1.153013,53.246075,357.5,2006,1,4
3,2006-01-05,280.938049,38.166538,26.218863,5.762608e-08,2.959347e-18,0.004525,277.417236,-3.568287,3.080430,53.246075,357.5,2006,1,5
4,2006-01-06,283.474579,11.456951,4.307912,6.502454e-08,7.293952e-15,0.005931,281.063141,0.618560,5.766347,53.246075,357.5,2006,1,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27369,2080-12-27,284.340881,61.076118,25.778275,6.237690e-09,5.984878e-19,0.004431,280.278046,5.466210,4.381413,53.246075,357.5,2080,12,362
27370,2080-12-28,283.297699,49.093731,20.703382,8.702459e-09,1.302840e-16,0.004670,279.387421,3.628653,3.683642,53.246075,357.5,2080,12,363
27371,2080-12-29,281.943665,28.313158,13.846190,3.092980e-09,5.006458e-18,0.004368,278.609833,1.699727,2.453841,53.246075,357.5,2080,12,364
27372,2080-12-30,281.938782,44.790138,22.579945,3.884140e-09,1.511830e-17,0.004444,278.205811,0.467049,2.685232,53.246075,357.5,2080,12,365
27373,2080-12-31,284.061890,14.020250,12.806109,1.407559e-07,3.668375e-15,0.005713,280.227600,-2.889111,4.893875,53.246075,357.5,2080,12,366

In [ ]:
# read 005
ds_005=xr.open_dataset("D:/Man/Earth and Environment/project2/005_2006_2080_352_360.nc")

ds_005_man=ds_005.sel(lat=man_lat,lon=man_lon,method='nearest')

if hasattr(ds_005_man.indexes['time'], 'to_datetimeindex'):
    datetime_index=ds_005_man.indexes['time'].to_datetimeindex()
    ds_005_man['time']=datetime_index

man_005=ds_005_man.to_dataframe().reset_index()

man_005['year']=man_005['time'].dt.year
man_005['month']=man_005['time'].dt.month
man_005['day']=man_005['time'].dt.day_of_year

man_005.to_csv("D:/Man/Earth and Environment/project2/005_manchester.csv",index=False)

man_005

C:\Users\Administrator\AppData\Local\Temp\ipykernel_6320\3463507429.py:7: FutureWarning: In a future version of xarray to_datetimeindex will default to returning a 'us'-resolution DatetimeIndex instead of a 'ns'-resolution DatetimeIndex. This warning can be silenced by explicitly passing the `time_unit` keyword argument.
  datetime_index = ds_005_man.indexes['time'].to_datetimeindex()
C:\Users\Administrator\AppData\Local\Temp\ipykernel_6320\3463507429.py:7: RuntimeWarning: Converting a CFTimeIndex with dates from a non-standard calendar, 'noleap', to a pandas.DatetimeIndex, which uses dates from the standard calendar.  This may lead to subtle errors in operations that depend on the length of time between dates.
  datetime_index = ds_005_man.indexes['time'].to_datetimeindex()

,time,TREFMXAV_U,FLNS,FSNS,PRECT,PRSN,QBOT,TREFHT,UBOT,VBOT,lat,lon,year,month,day
0,2006-01-02,284.302612,8.737288,7.855509,1.544201e-07,4.051599e-16,0.005373,279.221954,2.303055,4.502803,53.246075,357.5,2006,1,2
1,2006-01-03,286.163269,6.686464,7.501073,7.784098e-08,0.000000e+00,0.007595,284.198425,4.657475,3.158464,53.246075,357.5,2006,1,3
2,2006-01-04,286.310303,27.445148,12.188718,4.851411e-08,7.075068e-18,0.005667,282.420227,5.083677,5.835154,53.246075,357.5,2006,1,4
3,2006-01-05,288.008820,10.443632,4.354691,1.091676e-07,1.429017e-14,0.007362,284.972076,3.029053,8.031938,53.246075,357.5,2006,1,5
4,2006-01-06,283.935760,70.927299,31.532597,2.531009e-09,6.418103e-18,0.004160,280.298279,3.783906,6.986506,53.246075,357.5,2006,1,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27369,2080-12-27,281.936798,54.674797,30.739758,3.295916e-09,2.832929e-20,0.004050,276.110687,2.957903,0.200040,53.246075,357.5,2080,12,362
27370,2080-12-28,283.758606,17.237247,10.646000,2.152703e-08,1.689277e-23,0.005656,281.060974,5.143696,3.209976,53.246075,357.5,2080,12,363
27371,2080-12-29,285.953278,11.791540,6.422498,2.352653e-08,5.303063e-19,0.006324,283.697327,6.311730,3.368121,53.246075,357.5,2080,12,364
27372,2080-12-30,287.041016,15.233866,12.290892,1.370449e-08,0.000000e+00,0.007029,285.810883,6.767558,5.087225,53.246075,357.5,2080,12,365
27373,2080-12-31,286.128876,34.858963,16.604631,4.296313e-09,0.000000e+00,0.006423,283.500275,1.961040,4.853287,53.246075,357.5,2080,12,366

In [ ]:
# read 006
ds_006=xr.open_dataset("D:/Man/Earth and Environment/project2/006_2006_2080_352_360.nc")

ds_006_man=ds_006.sel(lat=man_lat,lon=man_lon,method='nearest')

if hasattr(ds_006_man.indexes['time'], 'to_datetimeindex'):
    datetime_index=ds_006_man.indexes['time'].to_datetimeindex()
    ds_006_man['time']=datetime_index

man_006=ds_006_man.to_dataframe().reset_index()

man_006['year']=man_006['time'].dt.year
man_006['month']=man_006['time'].dt.month
man_006['day']=man_006['time'].dt.day_of_year

man_006.to_csv("D:/Man/Earth and Environment/project2/006_manchester.csv",index=False)

man_006

C:\Users\Administrator\AppData\Local\Temp\ipykernel_6320\3822445889.py:7: FutureWarning: In a future version of xarray to_datetimeindex will default to returning a 'us'-resolution DatetimeIndex instead of a 'ns'-resolution DatetimeIndex. This warning can be silenced by explicitly passing the `time_unit` keyword argument.
  datetime_index = ds_006_man.indexes['time'].to_datetimeindex()
C:\Users\Administrator\AppData\Local\Temp\ipykernel_6320\3822445889.py:7: RuntimeWarning: Converting a CFTimeIndex with dates from a non-standard calendar, 'noleap', to a pandas.DatetimeIndex, which uses dates from the standard calendar.  This may lead to subtle errors in operations that depend on the length of time between dates.
  datetime_index = ds_006_man.indexes['time'].to_datetimeindex()

,time,TREFMXAV_U,FLNS,FSNS,PRECT,PRSN,QBOT,TREFHT,UBOT,VBOT,lat,lon,year,month,day
0,2006-01-02,281.783630,7.795940,5.284956,8.484563e-09,4.767665e-17,0.004884,278.642242,-0.688030,3.513100,53.246075,357.5,2006,1,2
1,2006-01-03,282.606598,6.680990,4.146327,4.012821e-08,3.675887e-15,0.005667,280.420105,0.005416,-2.804164,53.246075,357.5,2006,1,3
2,2006-01-04,282.299133,11.462930,5.328113,3.763157e-09,1.610562e-16,0.005132,280.067352,-2.432466,-1.538912,53.246075,357.5,2006,1,4
3,2006-01-05,281.223236,18.619301,11.026204,2.047969e-09,8.544233e-16,0.003768,277.904633,-3.002947,0.825787,53.246075,357.5,2006,1,5
4,2006-01-06,283.058319,14.055288,8.590136,2.003277e-09,7.844428e-20,0.005600,280.422150,-2.908460,2.013617,53.246075,357.5,2006,1,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27369,2080-12-27,280.948273,14.914908,10.439489,2.061167e-07,0.000000e+00,0.005174,277.903412,-0.844390,-4.662560,53.246075,357.5,2080,12,362
27370,2080-12-28,281.144287,39.223995,18.932810,1.417330e-08,6.265950e-17,0.004288,277.650574,6.115401,-0.257424,53.246075,357.5,2080,12,363
27371,2080-12-29,281.784576,65.748985,28.467485,3.500785e-10,2.476131e-17,0.004208,277.542267,6.853760,1.595987,53.246075,357.5,2080,12,364
27372,2080-12-30,280.664215,64.425964,24.496321,9.899002e-10,5.922713e-19,0.004285,275.348511,0.967602,1.682474,53.246075,357.5,2080,12,365
27373,2080-12-31,281.684082,21.064121,13.954908,2.935353e-08,3.262448e-14,0.005198,278.482178,0.155684,2.725878,53.246075,357.5,2080,12,366

In [7]:
# read 007
ds_007=xr.open_dataset("D:/Man/Earth and Environment/project2/007_2006_2080_352_360.nc")

ds_007_man=ds_007.sel(lat=man_lat,lon=man_lon,method='nearest')

if hasattr(ds_007_man.indexes['time'], 'to_datetimeindex'):
    datetime_index=ds_007_man.indexes['time'].to_datetimeindex()
    ds_007_man['time']=datetime_index

man_007=ds_007_man.to_dataframe().reset_index()

man_007['year']=man_007['time'].dt.year
man_007['month']=man_007['time'].dt.month
man_007['day']=man_007['time'].dt.day_of_year

man_007.to_csv("D:/Man/Earth and Environment/project2/007_manchester.csv",index=False)

man_007

C:\Users\Administrator\AppData\Local\Temp\ipykernel_6320\1421079003.py:7: FutureWarning: In a future version of xarray to_datetimeindex will default to returning a 'us'-resolution DatetimeIndex instead of a 'ns'-resolution DatetimeIndex. This warning can be silenced by explicitly passing the `time_unit` keyword argument.
  datetime_index=ds_007_man.indexes['time'].to_datetimeindex()
C:\Users\Administrator\AppData\Local\Temp\ipykernel_6320\1421079003.py:7: RuntimeWarning: Converting a CFTimeIndex with dates from a non-standard calendar, 'noleap', to a pandas.DatetimeIndex, which uses dates from the standard calendar.  This may lead to subtle errors in operations that depend on the length of time between dates.
  datetime_index=ds_007_man.indexes['time'].to_datetimeindex()

,time,TREFMXAV_U,FLNS,FSNS,PRECT,PRSN,QBOT,TREFHT,UBOT,VBOT,lat,lon,year,month,day
0,2006-01-02,282.063049,32.912292,9.570811,1.024123e-08,1.328980e-15,0.003757,279.914276,8.547442,0.224397,53.246075,357.5,2006,1,2
1,2006-01-03,283.699585,27.826134,18.303064,1.065816e-08,4.577285e-16,0.004989,279.756287,3.954805,1.289937,53.246075,357.5,2006,1,3
2,2006-01-04,282.064056,65.338554,28.210258,2.143026e-09,7.480785e-16,0.004033,277.990601,6.494915,-0.385829,53.246075,357.5,2006,1,4
3,2006-01-05,280.173309,38.994473,16.601635,4.274406e-08,1.316970e-14,0.004264,276.348663,-0.893610,0.834761,53.246075,357.5,2006,1,5
4,2006-01-06,279.308289,7.846845,3.547717,4.993412e-08,3.063486e-09,0.004556,277.276886,-4.548933,0.594513,53.246075,357.5,2006,1,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27369,2080-12-27,283.754669,39.801468,18.639786,3.262576e-08,7.263507e-17,0.004476,281.520233,6.240410,3.863839,53.246075,357.5,2080,12,362
27370,2080-12-28,290.714844,26.743248,17.816031,7.806167e-08,8.346240e-24,0.007808,286.230927,6.182361,7.725119,53.246075,357.5,2080,12,363
27371,2080-12-29,290.617828,54.174992,12.987561,4.443908e-08,3.344424e-16,0.004818,283.313477,9.753526,5.765684,53.246075,357.5,2080,12,364
27372,2080-12-30,282.042633,30.772768,7.853101,1.461955e-07,1.513967e-14,0.004490,278.699768,2.305171,0.630563,53.246075,357.5,2080,12,365
27373,2080-12-31,282.844604,38.660469,19.766939,1.083925e-08,5.731818e-15,0.004373,279.569092,6.856066,2.640167,53.246075,357.5,2080,12,366

In [8]:
# read 008
ds_008=xr.open_dataset("D:/Man/Earth and Environment/project2/008_2006_2080_352_360.nc")

ds_008_man=ds_008.sel(lat=man_lat,lon=man_lon,method='nearest')

if hasattr(ds_008_man.indexes['time'], 'to_datetimeindex'):
    datetime_index=ds_008_man.indexes['time'].to_datetimeindex()
    ds_008_man['time']=datetime_index

man_008=ds_008_man.to_dataframe().reset_index()

man_008['year']=man_008['time'].dt.year
man_008['month']=man_008['time'].dt.month
man_008['day']=man_008['time'].dt.day_of_year

man_008.to_csv("D:/Man/Earth and Environment/project2/008_manchester.csv",index=False)

man_008

C:\Users\Administrator\AppData\Local\Temp\ipykernel_6320\2996382552.py:7: FutureWarning: In a future version of xarray to_datetimeindex will default to returning a 'us'-resolution DatetimeIndex instead of a 'ns'-resolution DatetimeIndex. This warning can be silenced by explicitly passing the `time_unit` keyword argument.
  datetime_index=ds_008_man.indexes['time'].to_datetimeindex()
C:\Users\Administrator\AppData\Local\Temp\ipykernel_6320\2996382552.py:7: RuntimeWarning: Converting a CFTimeIndex with dates from a non-standard calendar, 'noleap', to a pandas.DatetimeIndex, which uses dates from the standard calendar.  This may lead to subtle errors in operations that depend on the length of time between dates.
  datetime_index=ds_008_man.indexes['time'].to_datetimeindex()

,time,TREFMXAV_U,FLNS,FSNS,PRECT,PRSN,QBOT,TREFHT,UBOT,VBOT,lat,lon,year,month,day
0,2006-01-02,284.532593,13.642488,12.411095,8.575076e-08,3.813165e-17,0.005496,279.626801,-1.441143,3.925679,53.246075,357.5,2006,1,2
1,2006-01-03,284.288055,39.296051,21.248678,1.471860e-08,1.962597e-17,0.005366,280.390015,3.266232,4.357970,53.246075,357.5,2006,1,3
2,2006-01-04,283.588257,24.336161,7.372517,7.370906e-08,1.449792e-17,0.005880,280.348389,2.110154,1.727758,53.246075,357.5,2006,1,4
3,2006-01-05,283.804718,34.057652,15.931653,6.393348e-08,1.598705e-17,0.004917,278.973877,1.468114,4.763241,53.246075,357.5,2006,1,5
4,2006-01-06,283.617218,32.591091,16.447544,3.944200e-08,1.348306e-12,0.004921,279.362274,2.744615,4.807573,53.246075,357.5,2006,1,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27369,2080-12-27,286.378754,17.438847,6.720299,3.892051e-08,7.616115e-15,0.006004,282.548523,2.741483,7.565282,53.246075,357.5,2080,12,362
27370,2080-12-28,286.621307,26.986507,12.976557,2.301632e-07,6.722780e-16,0.005813,281.885712,4.295599,7.222901,53.246075,357.5,2080,12,363
27371,2080-12-29,282.327393,41.652626,16.614481,2.653475e-08,1.264485e-15,0.004281,279.076965,3.328679,4.574871,53.246075,357.5,2080,12,364
27372,2080-12-30,281.410248,56.226501,24.193817,1.709695e-08,2.954024e-17,0.004289,277.916626,2.779102,4.442761,53.246075,357.5,2080,12,365
27373,2080-12-31,280.582733,46.781525,24.450218,1.749981e-08,1.094167e-12,0.004278,277.412048,-0.026990,3.524161,53.246075,357.5,2080,12,366